version: 0.2

phases:
  pre_build:
    commands:
      - echo "===== PRE BUILD ====="
      - echo "Starting CodeBuild..."
      - echo "Checking Docker..."
      - docker --version

  build:
    commands:
      - echo "===== BUILD ====="
      - echo "Building Docker image..."
      - docker build -t devops-app:latest .

  post_build:
    commands:
      - echo "===== POST BUILD ====="
      - echo "Docker image build completed."
      - echo "CodeBuild completed successfully."
